FROM ubuntu:bionic
MAINTAINER Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>

RUN apt-get update -qq && apt-get install -qq -o=Dpkg::Use-Pty=0 -y  gnupg && rm -rf /var/lib/apt/lists/*

COPY repo/windmaker-develop.list /etc/apt/sources.list.d/windmaker.list
COPY repo/WINDMAKER-GPG-KEY.pub /tmp/WINDMAKER-GPG-KEY.pub

RUN apt-get install gnupg && apt-get update -qq --allow-unauthenticated

ARG CACHE_DATE=2018-02-20

RUN apt-get install -qq -o=Dpkg::Use-Pty=0 -y toggl-jira-work-logger --no-install-recommends && rm -rf /var/lib/apt/lists/*
